### ISSUE TITLE
[2.0] Rainbow Mode

### ISSUE THREAD

**Issue by afouille** [gnugat-legacy/SoulMeMaybe#32]
Hi,

I'm surprised in a good way that SoolMeMaybe can now accurately change your connection status and the color associated with it. Blue! Green! White! Grey! Red! All these colors are beautiful and make me feel good.

Unfortunately, this application lack of a good rainbow mode. All these colors are good and whatnot, but there should be an option to make them change into all the spectrum several times per second. Like a rainbow of colored goodies. It would be so cool.

Thinks of the rainbow. That's a killer feature, and you know it.

Please, I need the rainbow so much,

**Comment by gnugat** [comment]
This is indeed a killer feature, and we might implement it before the 2.2 release :+1:

**Comment by gnugat** [comment]
Planned for the `2.0` release.

**Comment by gnugat** [comment]
[YOLO PHP](http://yolophp.com/) , the framework with SWAG, just gave birth to [fab-symfony-console](https://github.com/igorw/fab-symfony-console), a formatter making your output fabulous.

The current `rainbow mode` draws a rainbow in other NetSoul clients by changing the status quickly, but it makes SoulMeMaybe instable.
Instead, we could just use this formatter when the option is called :) .

**Comment by afouille** [comment]
Hi,

I'm deeply saddened to hear that the Rainbow Mode make your application instable. It is, indeed, problematic, and I think you should remove this functionnality instead of trying to code a software correctly.

In fact, it would be easier to remove the entire network layer of this application. These things are notoriously unreliable and shouldn't be trusted. You could just as easily fake an authentification by just printing "Connection Ok" on the console.

I know. It's not so easy to print something reliably. There is a good number of bugs that can arise when you println(), printf(), and all these functions. Nonetheless, I have faith in your capability as a programmer. You can do it. I'm sure.

If you have problems in the future, do not hesitate to ask me. I'm willing to help.

Cheer and thank you,

**Comment by gnugat** [comment]
Issue fixed with the following commit: https://github.com/gnugat/SoulMeMaybe/commit/69258016b2de86818de4f698158ef9cf1eb4acc4.

The old implementation of the rainbow mode only worked with people using some of the graphical clients and was flooding the logs (and console in verbose mode) of the user.
The new one will only be displayed to the user, but will make the console (in verbose mode) fabulous without flooding the logs.
